### ISSUE TITLE
can't see other device's video

### ISSUE THREAD

**Issue by aarush-paul** [vasanthv/ahey#37]
hello
i was testing the app on two of my devices on https://usetalk.io but i cant see the video neither can i hear the audio. i can see the other device join but no video or audio can be heard. pls help me out

**Comment by aarush-paul** [comment]
pls reply

**Comment by miroslavpejic85** [comment]
Hi @aarush-paul, 

Maybe because of the [Turn](https://webrtc.org/getting-started/turn-server) server.

[Here](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) you can check.

- A `STUN` server works if you can gather a candidate with type `srflx`
- A `TURN` server works if you can gather a candidate with type `relay`

I suggest to using only one Stun and one Turn as IceServers.

With this setting, probably it should work :)

```js
const ICE_SERVERS = [
    {
        "urls": "stun:stun.l.google.com:19302"
    },
    {
        "urls": "turn:openrelay.metered.ca:443",
        "username": "openrelayproject",
        "credential": "openrelayproject"
    }
];
```
Regards

**Comment by aarush-paul** [comment]
Thanks

**Comment by zakrian07** [comment]
sudo apt-get update
sudo apt-get install coturn
# Use fingerprint
fingerprint

# Set listening port
listening-port=3478

# Uncomment to use TLS/DTLS
#tls-listening-port=5349

# External IP address of the server
external-ip=your-ip

# Enable long-term credential mechanism
lt-cred-mech

# Set realm (any arbitrary string)
realm=myrealm

# User credentials (username:password)
user=username:password

# Enable relay
relay-ip=0.0.0.0

# Allowed peer IPs
allowed-peer-ip=0.0.0.0-255.255.255.255

# Total allocation bandwidth (in bytes per second)
bps-capacity=0

# Log file
log-file=/var/log/turnserver.log

# Verbose logging
verbose

# Enable full request/response logging
log-http-requests
just install your own server it will work so smooth
